apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nfroze/Project-12-MCP-Meets-K8s
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true