name: Application Security Pipeline

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/application-pipeline.yml'

env:
  DOCKER_IMAGE: nfroze/mcp-k8s-app

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Semgrep scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
        
    - name: Gitleaks scan
      uses: gitleaks/gitleaks-action@v2

    - name: Trivy dependency scan
      run: docker run --rm -v ${{ github.workspace }}/app:/app aquasec/trivy fs /app

    - name: Build image
      working-directory: ./app
      run: docker build -t ${{ env.DOCKER_IMAGE }}:latest .

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}:latest
        exit-code: '1'
        severity: 'CRITICAL'

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: docker push ${{ env.DOCKER_IMAGE }}:latest